version: '2'
services:
  web-pozos:
    image:  php:apache
    depends_on:
      - api-pozos
    ports:
      - "80:80"
    volumes:
      - ./website:/var/www/html
    environment:
      - USERNAME=toto
      - PASSWORD=python
    networks:
      - api-pozos

  api-pozos:
    image: api-pozos:v1
    volumes:
      - ./simple_api/student_age.json:/data/student_age.json
    networks:
      - api-pozos

networks:
  api-pozos:
